### ISSUE TITLE
Compilation error with Xcode 13

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#1259]
## Description

Changes introduced by 7da70cf9399e2703ac9cacbb6977edeb173de159 cause compilation errors with Xcode 13 :

<pre>
In file included from pandatool/src/gtk-stats/gtkstats_composite1.cxx:4:
pandatool/src/gtk-stats/gtkStatsGraph.cxx:277:5: error: call to 'encode_sRGB_float' is ambiguous
    encode_sRGB_float(rgb[0]),
    ^~~~~~~~~~~~~~~~~
built/include/convert_srgb.I:56:1: note: candidate function
encode_sRGB_float(unsigned char val) {
^
built/include/convert_srgb.I:69:1: note: candidate function
encode_sRGB_float(float val) {
^
In file included from pandatool/src/gtk-stats/gtkstats_composite1.cxx:4:
pandatool/src/gtk-stats/gtkStatsGraph.cxx:278:5: error: call to 'encode_sRGB_float' is ambiguous
    encode_sRGB_float(rgb[1]),
    ^~~~~~~~~~~~~~~~~
built/include/convert_srgb.I:56:1: note: candidate function
encode_sRGB_float(unsigned char val) {
^
built/include/convert_srgb.I:69:1: note: candidate function
encode_sRGB_float(float val) {
^
In file included from pandatool/src/gtk-stats/gtkstats_composite1.cxx:4:
pandatool/src/gtk-stats/gtkStatsGraph.cxx:279:5: error: call to 'encode_sRGB_float' is ambiguous
    encode_sRGB_float(rgb[2]));
    ^~~~~~~~~~~~~~~~~
built/include/convert_srgb.I:56:1: note: candidate function
encode_sRGB_float(unsigned char val) {
^
built/include/convert_srgb.I:69:1: note: candidate function
encode_sRGB_float(float val) {
^
In file included from pandatool/src/gtk-stats/gtkstats_composite1.cxx:4:
pandatool/src/gtk-stats/gtkStatsGraph.cxx:281:5: error: call to 'encode_sRGB_float' is ambiguous
    encode_sRGB_float(rgb[0] * 0.75f),
    ^~~~~~~~~~~~~~~~~
built/include/convert_srgb.I:56:1: note: candidate function
encode_sRGB_float(unsigned char val) {
^
built/include/convert_srgb.I:69:1: note: candidate function
encode_sRGB_float(float val) {
^
In file included from pandatool/src/gtk-stats/gtkstats_composite1.cxx:4:
pandatool/src/gtk-stats/gtkStatsGraph.cxx:282:5: error: call to 'encode_sRGB_float' is ambiguous
    encode_sRGB_float(rgb[1] * 0.75f),
    ^~~~~~~~~~~~~~~~~
built/include/convert_srgb.I:56:1: note: candidate function
encode_sRGB_float(unsigned char val) {
^
built/include/convert_srgb.I:69:1: note: candidate function
encode_sRGB_float(float val) {
^
In file included from pandatool/src/gtk-stats/gtkstats_composite1.cxx:4:
pandatool/src/gtk-stats/gtkStatsGraph.cxx:283:5: error: call to 'encode_sRGB_float' is ambiguous
    encode_sRGB_float(rgb[2] * 0.75f));
    ^~~~~~~~~~~~~~~~~
built/include/convert_srgb.I:56:1: note: candidate function
encode_sRGB_float(unsigned char val) {
^
built/include/convert_srgb.I:69:1: note: candidate function
encode_sRGB_float(float val) {
^
In file included from pandatool/src/gtk-stats/gtkstats_composite1.cxx:5:
pandatool/src/gtk-stats/gtkStatsLabel.cxx:58:5: error: call to 'encode_sRGB_float' is ambiguous
    encode_sRGB_float(rgb[0]),
    ^~~~~~~~~~~~~~~~~
built/include/convert_srgb.I:56:1: note: candidate function
encode_sRGB_float(unsigned char val) {
^
built/include/convert_srgb.I:69:1: note: candidate function
encode_sRGB_float(float val) {
^
In file included from pandatool/src/gtk-stats/gtkstats_composite1.cxx:5:
pandatool/src/gtk-stats/gtkStatsLabel.cxx:59:5: error: call to 'encode_sRGB_float' is ambiguous
    encode_sRGB_float(rgb[1]),
    ^~~~~~~~~~~~~~~~~
built/include/convert_srgb.I:56:1: note: candidate function
encode_sRGB_float(unsigned char val) {
^
built/include/convert_srgb.I:69:1: note: candidate function
encode_sRGB_float(float val) {
^
In file included from pandatool/src/gtk-stats/gtkstats_composite1.cxx:5:
pandatool/src/gtk-stats/gtkStatsLabel.cxx:60:5: error: call to 'encode_sRGB_float' is ambiguous
    encode_sRGB_float(rgb[2]));
    ^~~~~~~~~~~~~~~~~
built/include/convert_srgb.I:56:1: note: candidate function
encode_sRGB_float(unsigned char val) {
^
built/include/convert_srgb.I:69:1: note: candidate function
encode_sRGB_float(float val) {
^
In file included from pandatool/src/gtk-stats/gtkstats_composite1.cxx:5:
pandatool/src/gtk-stats/gtkStatsLabel.cxx:63:5: error: call to 'encode_sRGB_float' is ambiguous
    encode_sRGB_float(rgb[0] * 0.75f),
    ^~~~~~~~~~~~~~~~~
built/include/convert_srgb.I:56:1: note: candidate function
encode_sRGB_float(unsigned char val) {
^
built/include/convert_srgb.I:69:1: note: candidate function
encode_sRGB_float(float val) {
^
In file included from pandatool/src/gtk-stats/gtkstats_composite1.cxx:5:
pandatool/src/gtk-stats/gtkStatsLabel.cxx:64:5: error: call to 'encode_sRGB_float' is ambiguous
    encode_sRGB_float(rgb[1] * 0.75f),
    ^~~~~~~~~~~~~~~~~
built/include/convert_srgb.I:56:1: note: candidate function
encode_sRGB_float(unsigned char val) {
^
built/include/convert_srgb.I:69:1: note: candidate function
encode_sRGB_float(float val) {
^
In file included from pandatool/src/gtk-stats/gtkstats_composite1.cxx:5:
pandatool/src/gtk-stats/gtkStatsLabel.cxx:65:5: error: call to 'encode_sRGB_float' is ambiguous
    encode_sRGB_float(rgb[2] * 0.75f));
    ^~~~~~~~~~~~~~~~~
built/include/convert_srgb.I:56:1: note: candidate function
encode_sRGB_float(unsigned char val) {
^
built/include/convert_srgb.I:69:1: note: candidate function
encode_sRGB_float(float val) {
^
</pre>

## Steps to Reproduce

Checkout f30e87e7d1f48a5f46fefad5b8fba57296363ea6 and build using Xcode 13

## Environment
 * Operating system: macOS
 * System architecture: x86
 * Panda3D version: f30e87e7d1f48a5f46fefad5b8fba57296363ea6
 * Installation method: built from source
 * Python version (if using Python): 3.7
 * Compiler (if using C++): clang 13.0.0

**Comment by el-dee** [comment]
It is compiled using STDFLOAT_DOUBLE=1 ;)
