### ISSUE TITLE
attribute error

### ISSUE THREAD

**Issue by abtechmg** [panda3d/panda3d#380]
Hi, i'm running Panda3D on Python 3 and i get errors like these a lot. I tried hacking together DirectScrolledList to fix the issue, but nothing really fixed it.

```  File "C:\Panda3D-1.10.0-x64\direct\gui\DirectScrolledList.py", line 109, in __init__
    item.reparentTo(self.itemFrame)
AttributeError: 'bytes' object has no attribute 'reparentTo'
```

Curious if this will be fixed or if something changed here that i'm unaware of.

**Comment by rdb** [comment]
We will need to see some code of yours to see what the problem might be.  Because it looks like you are passing a `bytes` object as item in a DirectScrolledList, which is not valid.

**Comment by abtechmg** [comment]
Ended up compiling latest development build with Python 2.7 rather than 3.6 and it works fine. Not sure what's going on with that. But it's working now that I've done that.

**Comment by rdb** [comment]
That is because Python 2 does not distinguish between `str` and `bytes` types, so whatever mistake may be in the invoking code (or in Panda, if this is indeed a bug) may go unnoticed.  But you are likely to run into this again when you inevitably have to port your code to Python 3 when Python 2 goes EOL.
