### ISSUE TITLE
panda3d.core.MainThread issue in tkRun

### ISSUE THREAD

**Issue by consultit** [panda3d/panda3d#226]
By running this code with panda3d's latest commit build (on Debian 9.3)
```
from panda3d.core import load_prc_file_data
from direct.showbase.ShowBase import ShowBase

load_prc_file_data("", "want-directtools #t")
load_prc_file_data("", "want-tk #t")

if __name__ == '__main__':
    app = ShowBase()
    app.run()
```
 I get this error:
```
Traceback (most recent call last):
 ...
  File "/usr/share/panda3d/direct/showbase/ShowBase.py", line 2990, in tkRun
    if Thread.getCurrentThread().getCurrentTask():
AttributeError: 'panda3d.core.MainThread' object has no attribute 'getCurrentTask'
```
Bye

**Comment by rdb** [comment]
Regression caused by 2e20a0f16ed4c08030f978e46950ba635fca8a32 .  I'm on it.
