### ISSUE TITLE
Build fails when using openCV 4.x

### ISSUE THREAD

**Issue by susnux** [panda3d/panda3d#697]
There are some issues when building with openCV 4.x (as available on openSUSE Tumbleweed).
The build errors are:

> [  287s] [T8] Building C++ object built/tmp/cpython-27mu/libp3vision_igate.o
> [  287s] In file included from panda/src/vision/p3vision_composite1.cxx:3:
> [  287s] panda/src/vision/openCVTexture.cxx: In member function ‘bool OpenCVTexture::do_reconsider_video_properties(Texture::CData*, const OpenCVTexture::VideoStream&, int, int, const LoaderOptions&)’:
> [  287s] panda/src/vision/openCVTexture.cxx:199:56: error: ‘CV_CAP_PROP_FPS’ was not declared in this scope
> [  287s]   199 |     frame_rate = cvGetCaptureProperty(stream._capture, CV_CAP_PROP_FPS);
> [  287s]       |                                                        ^~~~~~~~~~~~~~~
> [  287s] panda/src/vision/openCVTexture.cxx:199:18: error: ‘cvGetCaptureProperty’ was not declared in this scope
> [  287s]   199 |     frame_rate = cvGetCaptureProperty(stream._capture, CV_CAP_PROP_FPS);
> [  287s]       |                  ^~~~~~~~~~~~~~~~~~~~
> [  287s] panda/src/vision/openCVTexture.cxx:200:61: error: ‘CV_CAP_PROP_FRAME_COUNT’ was not declared in this scope
> [  287s]   200 |     num_frames = (int)cvGetCaptureProperty(stream._capture, CV_CAP_PROP_FRAME_COUNT);
> [  287s]       |                                                             ^~~~~~~~~~~~~~~~~~~~~~~
> [  287s] panda/src/vision/openCVTexture.cxx:215:58: error: ‘CV_CAP_PROP_FRAME_WIDTH’ was not declared in this scope
> [  287s]   215 |   int width = (int)cvGetCaptureProperty(stream._capture, CV_CAP_PROP_FRAME_WIDTH);
> [  287s]       |                                                          ^~~~~~~~~~~~~~~~~~~~~~~
> [  287s] panda/src/vision/openCVTexture.cxx:215:20: error: ‘cvGetCaptureProperty’ was not declared in this scope
> [  287s]   215 |   int width = (int)cvGetCaptureProperty(stream._capture, CV_CAP_PROP_FRAME_WIDTH);
> [  287s]       |                    ^~~~~~~~~~~~~~~~~~~~
> [  287s] panda/src/vision/openCVTexture.cxx:216:59: error: ‘CV_CAP_PROP_FRAME_HEIGHT’ was not declared in this scope
> [  287s]   216 |   int height = (int)cvGetCaptureProperty(stream._capture, CV_CAP_PROP_FRAME_HEIGHT);
> [  287s]       |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~
> [  287s] panda/src/vision/openCVTexture.cxx: In member function ‘bool OpenCVTexture::VideoStream::get_frame_data(int, const unsigned char*&, const unsigned char*&, const unsigned char*&, int&, int&)’:
> [  287s] panda/src/vision/openCVTexture.cxx:545:36: error: ‘CV_CAP_PROP_POS_FRAMES’ was not declared in this scope
> [  287s]   545 |     cvSetCaptureProperty(_capture, CV_CAP_PROP_POS_FRAMES, frame);
> [  287s]       |                                    ^~~~~~~~~~~~~~~~~~~~~~
> [  287s] panda/src/vision/openCVTexture.cxx:545:5: error: ‘cvSetCaptureProperty’ was not declared in this scope
> [  287s]   545 |     cvSetCaptureProperty(_capture, CV_CAP_PROP_POS_FRAMES, frame);
> [  287s]       |     ^~~~~~~~~~~~~~~~~~~~
> [  287s] panda/src/vision/openCVTexture.cxx:549:3: error: ‘IplImage’ was not declared in this scope
> [  287s]   549 |   IplImage *image = cvQueryFrame(_capture);
> [  287s]       |   ^~~~~~~~
> [  287s] panda/src/vision/openCVTexture.cxx:549:13: error: ‘image’ was not declared in this scope; did you mean ‘arImage’?
> [  287s]   549 |   IplImage *image = cvQueryFrame(_capture);
> [  287s]       |             ^~~~~
> [  287s]       |             arImage
> [  287s] panda/src/vision/openCVTexture.cxx:549:21: error: ‘cvQueryFrame’ was not declared in this scope
> [  287s]   549 |   IplImage *image = cvQueryFrame(_capture);
> [  287s]       |                     ^~~~~~~~~~~~
> [  287s] panda/src/vision/openCVTexture.cxx: In member function ‘bool OpenCVTexture::VideoStream::read(const Filename&)’:
> [  287s] panda/src/vision/openCVTexture.cxx:591:14: error: ‘cvCaptureFromFile’ was not declared in this scope
> [  287s]   591 |   _capture = cvCaptureFromFile(os_specific.c_str());
> [  287s]       |              ^~~~~~~~~~~~~~~~~
> [  287s] panda/src/vision/openCVTexture.cxx: In member function ‘bool OpenCVTexture::VideoStream::from_camera(int)’:
> [  287s] panda/src/vision/openCVTexture.cxx:607:14: error: ‘cvCaptureFromCAM’ was not declared in this scope
> [  287s]   607 |   _capture = cvCaptureFromCAM(camera_index);
> [  287s]       |              ^~~~~~~~~~~~~~~~
> [  287s] panda/src/vision/openCVTexture.cxx: In member function ‘void OpenCVTexture::VideoStream::clear()’:
> [  287s] panda/src/vision/openCVTexture.cxx:621:5: error: ‘cvReleaseCapture’ was not declared in this scope
> [  287s]   621 |     cvReleaseCapture(&_capture);
> [  287s]       |     ^~~~~~~~~~~~~~~~
> [  287s] [T5] Building Interrogate object built/tmp/cpython-27mu/vision_module.o
> [  287s] In file included from panda/src/vision/p3vision_composite1.cxx:5:
> [  287s] panda/src/vision/webcamVideoCursorOpenCV.cxx: In constructor ‘WebcamVideoCursorOpenCV::WebcamVideoCursorOpenCV(WebcamVideoOpenCV*)’:
> [  287s] panda/src/vision/webcamVideoCursorOpenCV.cxx:42:14: error: ‘cvCaptureFromCAM’ was not declared in this scope
> [  287s]    42 |   _capture = cvCaptureFromCAM(src->_camera_index);
> [  287s]       |              ^~~~~~~~~~~~~~~~
> [  287s] Referencing Library libp3vision
> [  287s] panda/src/vision/webcamVideoCursorOpenCV.cxx:44:51: error: ‘CV_CAP_PROP_FRAME_WIDTH’ was not declared in this scope
> [  287s]    44 |     _size_x = (int)cvGetCaptureProperty(_capture, CV_CAP_PROP_FRAME_WIDTH);
> [  287s]       |                                                   ^~~~~~~~~~~~~~~~~~~~~~~
> [  287s] panda/src/vision/webcamVideoCursorOpenCV.cxx:44:20: error: ‘cvGetCaptureProperty’ was not declared in this scope
> [  287s]    44 |     _size_x = (int)cvGetCaptureProperty(_capture, CV_CAP_PROP_FRAME_WIDTH);
> [  287s]       |                    ^~~~~~~~~~~~~~~~~~~~
> [  287s] panda/src/vision/webcamVideoCursorOpenCV.cxx:45:51: error: ‘CV_CAP_PROP_FRAME_HEIGHT’ was not declared in this scope
> [  287s]    45 |     _size_y = (int)cvGetCaptureProperty(_capture, CV_CAP_PROP_FRAME_HEIGHT);
> [  287s]       |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~
> [  287s] panda/src/vision/webcamVideoCursorOpenCV.cxx: In destructor ‘virtual WebcamVideoCursorOpenCV::~WebcamVideoCursorOpenCV()’:
> [  287s] panda/src/vision/webcamVideoCursorOpenCV.cxx:56:5: error: ‘cvReleaseCapture’ was not declared in this scope
> [  287s]    56 |     cvReleaseCapture(&_capture);
> [  287s]       |     ^~~~~~~~~~~~~~~~
> [  287s] panda/src/vision/webcamVideoCursorOpenCV.cxx: In member function ‘bool WebcamVideoCursorOpenCV::get_frame_data(const unsigned char*&, const unsigned char*&, const unsigned char*&, int&, int&)’:
> [  287s] panda/src/vision/webcamVideoCursorOpenCV.cxx:136:3: error: ‘IplImage’ was not declared in this scope
> [  287s]   136 |   IplImage *image = cvQueryFrame(_capture);
> [  287s]       |   ^~~~~~~~
> [  287s] panda/src/vision/webcamVideoCursorOpenCV.cxx:136:13: error: ‘image’ was not declared in this scope; did you mean ‘arImage’?
> [  287s]   136 |   IplImage *image = cvQueryFrame(_capture);
> [  287s]       |             ^~~~~
> [  287s]       |             arImage
> [  287s] panda/src/vision/webcamVideoCursorOpenCV.cxx:136:21: error: ‘cvQueryFrame’ was not declared in this scope
> [  287s]   136 |   IplImage *image = cvQueryFrame(_capture);
> [  287s]       |                     ^~~~~~~~~~~~
> [  287s] In file included from panda/src/vision/p3vision_composite1.cxx:6:
> [  287s] panda/src/vision/webcamVideoCursorV4L.cxx: In member function ‘virtual PointerTo<MovieVideoCursor::Buffer> WebcamVideoCursorV4L::fetch_buffer()’:
> [  287s] panda/src/vision/webcamVideoCursorV4L.cxx:457:22: warning: comparison of integer expressions of different signedness: ‘int’ and ‘JDIMENSION’ {aka ‘unsigned int’} [-Wsign-compare]
> [  287s]   457 |           && _size_x == _cinfo.output_width && _size_y == _cinfo.output_height) {
> [  287s]       |              ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
> [  287s] panda/src/vision/webcamVideoCursorV4L.cxx:457:56: warning: comparison of integer expressions of different signedness: ‘int’ and ‘JDIMENSION’ {aka ‘unsigned int’} [-Wsign-compare]
> [  287s]   457 |           && _size_x == _cinfo.output_width && _size_y == _cinfo.output_height) {
> [  287s]       |                                                ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
> [  287s] panda/src/vision/webcamVideoCursorV4L.cxx:496:30: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
> [  287s]   496 |     for (size_t row = 0; row < _size_y; ++row) {
> [  287s]       |                          ~~~~^~~~~~~~~
> [  287s] panda/src/vision/webcamVideoCursorV4L.cxx:511:30: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
> [  287s]   511 |     for (size_t row = 0; row < _size_y; ++row) {
> [  287s]       |                          ~~~~^~~~~~~~~
> [  287s] panda/src/vision/webcamVideoCursorV4L.cxx:520:30: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
> [  287s]   520 |     for (size_t row = 0; row < _size_y; ++row) {
> [  288s]       |                          ~~~~^~~~~~~~~
> [  288s] panda/src/vision/webcamVideoCursorV4L.cxx:531:30: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
> [  288s]   531 |     for (size_t row = 0; row < _size_y; ++row) {
> [  288s]       |                          ~~~~^~~~~~~~~
> [  288s] [T6] Building C++ object built/tmp/pandafx_pandafx.o
> [  289s] [T6] Building C++ object built/tmp/openal_audio_openal_audio_composite1.o
> [  289s] The following command returned a non-zero value: g++ -std=gnu++11 -ftemplate-depth-70 -fPIC -c -o built/tmp/p3vision_composite1.o -Ibuilt/tmp -Ibuilt/include -DHAVE_OPENCV= -DOPENCV_VER_23= -Ipanda/src/vision -fvisibility=hidden -pthread -fexceptions -msse2 -fno-strict-aliasing -ffast-math -fno-stack-protector -fno-finite-math-only -fno-unsafe-math-optimizations -O2 -Wall -Wno-unused-function -Wno-reorder  -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=8 -fno-strict-aliasing -DBUILDING_VISION panda/src/vision/p3vision_composite1.cxx

**Comment by rdb** [comment]
Thanks.  I would suggest to compile with `--no-opencv` as we don't use OpenCV for anything important on Linux (since we already support Video4Linux for webcam input).

**Comment by ChinYing-Li** [comment]
If no one's working on this one, I would like to take ths issue.

**Comment by Moguri** [comment]
As far as I know, no one is working on this issue.

**Comment by ChinYing-Li** [comment]
Alright, thanks.

**Comment by ChinYing-Li** [comment]
An update: I could not reproduce the compilation error; panda3d can be built successfully with opencv 4.2; however I did not expected it to build successfully! 
OS: `Ubuntu 20.04`
OpenCV version: 4.2

This seems highly relevant to the build error posted by @susnux :
[https://stackoverflow.com/questions/57982505/opencv-4-cap-prop-pos-frames-was-not-declared-in-this-scope]

**Comment by rdb** [comment]
Closing as unable to reproduce, builds fine with OpenCV 4.6.
