### ISSUE TITLE
shadergenerator fails to create shaders after f79fbf2

### ISSUE THREAD

**Issue by ptc-meichner** [panda3d/panda3d#156]
:shader(error): Failed to compile Cg shader created-shader:
(98) : error C1038: declaration of "vtx_tangent" conflicts with previous declaration at (94)
(99) : error C1038: declaration of "vtx_binormal" conflicts with previous declaration at (95)
(100) : error C1038: declaration of "l_tangent" conflicts with previous declaration at (96)
(101) : error C1038: declaration of "l_binormal" conflicts with previous declaration at (97)

and here's the corresponding vshader that failed to compile:
void vshader(
         in float4 vtx_texcoord : TEXCOORD0,
         out float4 l_texcoord : TEXCOORD0,
         in float4 vtx_tangent : TEXCOORD1,
         in float4 vtx_binormal : TEXCOORD2,
         out float4 l_tangent : TEXCOORD1,
         out float4 l_binormal : TEXCOORD2,
         in float4 vtx_tangent : TEXCOORD3,
         in float4 vtx_binormal : TEXCOORD4,
         out float4 l_tangent : TEXCOORD3,
         out float4 l_binormal : TEXCOORD4,
         uniform float4x4 trans_model_to_view,
         out float4 l_eye_position : TEXCOORD5,
         uniform float4x4 tpose_view_to_model,
         out float4 l_eye_normal : TEXCOORD6,
         in float3 vtx_normal : NORMAL,
         in float4 vtx_position : POSITION,
         out float4 l_position : POSITION,
         uniform float4x4 mat_modelproj
) {
         l_position = mul(mat_modelproj, vtx_position);
         l_eye_position = mul(trans_model_to_view, vtx_position);
         l_eye_normal.xyz = normalize(mul((float3x3)tpose_view_to_model, vtx_normal));
         l_eye_normal.w = 0;
         l_texcoord = vtx_texcoord;
         l_tangent.xyz = normalize(mul((float3x3)trans_model_to_view, vtx_tangent.xyz));
         l_tangent.w = 0;
         l_binormal.xyz = normalize(mul((float3x3)trans_model_to_view, -vtx_binormal.xyz));
         l_binormal.w = 0;
}

**Comment by rdb** [comment]
Could you include the comment at the top of the shader indicating the
render state it was generated for?

**Comment by ptc-meichner** [comment]
ah of course, sorry for that:
/* Generated shader for render state:
  AntialiasAttrib: auto
  CullFaceAttrib:cull_none
  LightAttrib:on
    render/ambientLight
    render/lightRotator/dirLight1
    render/lightRotator/dirLight2
    render/lightRotator/dirLight3
  MaterialAttrib:Material B_M_SR a(0 0 0 1) d(0.439216 0.44549 0.454902 1) s(0.164706 0.167059 0.170588 1) e(0 0 0 1) s100 l0 t0
  RescaleNormalAttrib:rescale
  ShaderAttrib:auto
  TextureAttrib:on Bump.040:V12_R Bump.041:V12_R
*/

**Comment by ptc-meichner** [comment]
i guess the fix would be to add an additonal condition into line 623:
old:  if (tex._flags & (ShaderKey::TF_map_normal | ShaderKey::TF_map_height))
new:  if (map_index_normal < 0 && (tex._flags & (ShaderKey::TF_map_normal | ShaderKey::TF_map_height)))
as there is no real support for multiple normal maps in the generator
this will effectively use the first encountered one
does it make sense?

**Comment by rdb** [comment]
Yeah, but I realised it isn't that hard to add support for multiple normal maps, so I did that instead. :-)

Thanks for reporting the issue!

**Comment by ptc-meichner** [comment]
awsome, thanks!
