### ISSUE TITLE
Compilation issues for MacOs Mojave 10.14.6

### ISSUE THREAD

**Issue by Incubatio** [panda3d/panda3d#767]
Right now getting a working version of panda3d on macOS is a nest of issues, like Matryoshka dolls.

Short story:
=========
I would recommend any new panda3d dev and contributor to work on linux, installing a new OS is A LOT shorter and almost painless.

Long Story:
=========
Using Mac Os Mojave:
1. Tried several released version of panda3D SDK from the website => has several issue running existing projects (those issue are well documented and invite to compile panda3d from source),

> Undefined symbols for architecture x86_64:
"AmbientLight::AmbientLight(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&)", referenced from:
generateLights(NodePath, bool) in 3d-game-shaders-for-beginners.o
"InternalName::append(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&)"

2. Tried to compile panda3D from sources, doesn't work, has to re-compile third parties first,
> Undefined symbols for architecture x86_64:
  "std::__throw_length_error(char const*)", referenced from:
      std::vector<dxAABB, std::allocator<dxAABB> >::_M_insert_aux(__gnu_cxx::__normal_iterator<dxAABB*, std::vector<dxAABB, std::allocator<dxAABB> > >, dxAABB const&) in libode.a(collision_space.cpp.o)

3. Third parties doesn't compile either

> panda3d-thirdparty/build/bullet-prefix/src/bullet/src/LinearMath/btVector3.h:330:7: error: argument value 10880 is outside the valid range [0, 255] [-Wargument-outside-range]

> panda3d-thirdparty/build/bullet-prefix/src/bullet/src/LinearMath/btMatrix3x3.h:882:17: error: argument value 10880 is outside the valid range [0, 255] [-Wargument-outside-range]

====

Anyway I stopped there, I don't intend to try to find and fix third party issues when I just wanted to try few projects. And actually in parallel of all that, I had a linux machine running which took me 30 min to setup from scratch.

**Comment by Incubatio** [comment]
After removing bullet physics, I got this when compiling openssl:
Undefined symbols for architecture x86_64:
  "_ENGINE_load_gost", referenced from:
      _ENGINE_load_builtin_engines in libcrypto.a(eng_all.o)

**Comment by el-dee** [comment]
Most of your problems boil down to the fact that Panda3D and its dependencies are build using Mac0S 10.6 SDK (or even 10.4 for some of the third party packages), and that version of the SDK use libstdc++ instead of libc++ like the more recent SDK. So, in order to rebuild Panda3D or build C++ modules you have to also use the 10.6 SDK. Installing it is a bit tricky, but it allows you to build Panda3D with Mojave without a hitch (well at least on my setup ;) ) and build extensions (See https://discourse.panda3d.org/t/problems-with-macos-mojave/25254)

Also the long term plan is to drop support of 10.6 and set the baseline to 10.9 to avoid those kind of issues in the future, see  https://github.com/panda3d/panda3d/issues/300

**Comment by rdb** [comment]
If you wish to start a discussion, the bug tracker is not the right place for that.  I would invite you to use the [discussion boards](https://discourse.panda3d.org/) instead, or file individual bug reports the panda3d-thirdparty repo for compilation issues with that.

@el-dee is correct that we have dropped support for 10.6 on the master branch of GitHub and we have instead moved to 10.9 as the minimum, and libc++ is now used.  So, using the Panda3D 1.10.4.1 thirdparty packages won't work with the master branch.  The issue with compiling Panda3D is known and tracked in #584, but as this isn't really a bug in Panda3D, the best we can do is publish a recompiled thirdparty archive somewhere.

I'm not sure which issues you are referring to regarding the SDK.  I'd like to know why the SDK is not working on Mojave.  (I know it doesn't work on Catalina; you have to use `pip install panda3d` there for now, see #760 .)

**Comment by rdb** [comment]
The Bullet issue appears to have been fixed upstream:
https://github.com/bulletphysics/bullet3/pull/2232
We can change the panda3d-thirdparty script to patch it or to just update to a newer Bullet version.
